services:
  - type: web
    name: graphrag
    env: python
    buildCommand: |
      cd UI && npm install --save-dev vite && npm install && npm run build && cd .. && mkdir -p static && cp -r UI/dist/* static/ && pip install -r requirements.txt
    startCommand: uvicorn graphrag_api:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DEEPSEEK_API_KEY
        sync: false
      - key: NODE_VERSION
        value: 18.17.0
